# Generated by Django 3.1.4 on 2021-01-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='curry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rice',
            name='category',
        ),
    ]
