# Generated by Django 3.1.4 on 2020-12-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('BREAKFIRST', 'උදේ'), ('LUNCH', 'දවල්'), ('DINNER', 'රාත්\u200dරි'), ('SNACK', 'බයිට්')], max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('is_stock_avalable', models.BooleanField(default=True)),
            ],
        ),
    ]
