# Generated by Django 3.1.4 on 2020-12-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('total', models.IntegerField()),
                ('phone_no', models.ImageField(upload_to='')),
                ('adress', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('conform', 'conform'), ('dilever', 'dilever')], max_length=50)),
            ],
        ),
    ]
