# Generated by Django 3.1.4 on 2020-12-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
